DVAD-2991: convert drone.yml to 1.0 version
UKHomeOffice/lev-api pull request #104
Opened 2021-12-01 09:15 UTC by Cotterale

+ Using "drone convert --save" command
+ Add kubernetes type to drone file

2021-12-01 11:28 UTC, rageshrav submitted a review, later dismissed

2021-12-02 12:02 UTC, rageshrav commented on .drone.yml
> +    drone_server: https://drone-gitlab.acp.homeoffice.gov.uk
new drone server url required here

2021-12-03 09:20 UTC, JamesWoodwardHMPO commented on .drone.yml
> +    - 0.16.4-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}
Tags should be in double quotes to avoid some strange drone/yaml behaviour.

2021-12-03 09:21 UTC, JamesWoodwardHMPO commented on .drone.yml
> +    - 0
Remove this tag

2021-12-03 09:21 UTC, JamesWoodwardHMPO commented on .drone.yml
> +    TAG: 0.16.4-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}
Double quotes here too please

2021-12-03 09:22 UTC, JamesWoodwardHMPO requested changes
Looks good, with a few minor changes (see comments)

2021-12-03 11:52 UTC, JamesWoodwardHMPO approved these changes

2021-12-03 11:57 UTC, merged